### ISSUE TITLE
Your fork look better than the original one !

### ISSUE THREAD

**Issue by riderx** [skjnldsv/vue-plyr#11]
Do you have any plan to release it on npm ?
Since the author look dead, it can be nice to have yours instead !

**Comment by riderx** [comment]
Found it `npm i @skjnldsv/vue-plyr` thanks i hope that fix my issue

**Comment by skjnldsv** [comment]
Ahah, thanks!
haven't done much, but yeah, it was a bit stuck on the original repo :)

**Comment by skjnldsv** [comment]
Feel free to contribute here :tada:

**Comment by eliaschampi** [comment]
Thanks man, this package works great.

**Comment by lhoucinecherif** [comment]
Thanks so much , the only Plyr Component that works as expected for nuxt3 ,  I've struggled a weeks with the original one
