### ISSUE TITLE
Failed to resolve component: vue-plyr

### ISSUE THREAD

**Issue by IvanPerezChan** [skjnldsv/vue-plyr#339]
When installing the package and registering them in NUXT 3 rc 08 it works perfectly but when running the project it generates a message: **Failed to resolve component: vue-plyr** which I would like to know, is there no need to do anything else?

and I used this example to base myself
example: https://github.com/redxtech/vue-plyr/tree/master/examples/nuxt
![image](https://user-images.githubusercontent.com/95500418/193951513-dd1fca43-3a4e-4ed4-ae68-7a08142fd9b0.png)

**Comment by lhoucinecherif** [comment]
@IvanPerezChan You should add <ClientOnly> before the player Component :
```
 <ClientOnly>
        <VuePlyr>
             ...
```
(Even if you are using it as a plugin in client mode.)

**Comment by skjnldsv** [comment]
https://github.com/skjnldsv/vue-plyr/blob/4eb2f30cab82784764c4296c70e5bc2f6c8d0827/examples/nuxt/components/demo.vue#L10
