### ISSUE TITLE
loader problem

### ISSUE THREAD

**Issue by bluelemonade** [skjnldsv/vue-plyr#433]
I got following error:

in ./node_modules/@skjnldsv/vue-plyr/dist/index.esm.js
Module parse failed: Unexpected token (1:57119)
...
|...
| var script = {

here's the package.json

{
  "name": "prjektname",
  "version": "0.2.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.18.6",
    "@skjnldsv/vue-plyr": "^7.3.1",
    "@vueuse/components": "^9.12.0",
    "@vueuse/core": "^9.12.0",
    "chroma-js": "^2.4.2",
    "core-js": "^3.6.5",
    "mitt": "^3.0.0",
    "normalize.css": "^8.0.1",
    "patch-package": "^6.5.1",
    "postcss-preset-env": "^8.3.2",
    "simplex-noise": "^3.0.1",
    "stats.js": "^0.17.0",
    "swiper": "^7.4.1",
    "vue": "^3.0.0",
    "vue-router": "^4.1.2",
    "vue3-spring": "^0.0.2",
    "vue3-touch-events": "^4.1.0",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.15",
    "@vue/cli-plugin-eslint": "~4.5.15",
    "@vue/cli-service": "~4.5.15",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.53.0",
    "sass-loader": "^10.2.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by skjnldsv** [comment]
I'm guessing you have badly setup your dev env and it's importing the wrong export (esm vs cjs)
Feel free to check the examples, they're all working
