### ISSUE TITLE
Updating Node Dependency in NPM version

### ISSUE THREAD

**Issue by klepfish** [skjnldsv/vue-plyr#486]
Would it be possible to release this update as version 7.3.2 in NPM?
https://github.com/skjnldsv/vue-plyr/commit/551225b411123e7ecb3a202145f0390ec4688ec3

Would help in getting the Node dependencies all aligned.

Or if there's a way we can specifically deploy this on our end I'm open to suggestions.

Thank you for your help!

**Comment by skjnldsv** [comment]
https://github.com/skjnldsv/vue-plyr/releases/tag/v7.4.0

**Comment by klepfish** [comment]
Thank you!
