### ISSUE TITLE
Support for npm version 10

### ISSUE THREAD

**Issue by Ootsab** [skjnldsv/vue-plyr#550]
Recently, I upgraded my project's node version to 20 which also upgraded the npm version to 10 and this package supports node version 20 but not npm version 10.
Can you please add the support for npm 10?

```
Unsupported engine {
 package: '@skjnldsv/vue-plyr@7.4.0',
 required: { node: '^18.0.0 || ^20.0.0', npm: '^9.0.0' },
 current: { node: 'v20.12.2', npm: '10.5.0' }
}
```

**Comment by skjnldsv** [comment]
Done

**Comment by Ootsab** [comment]
Thank you very much!
